name: Update readme

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      # - name: Set up Python 3.11
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.11'

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install -y ffmpeg
          python -m pip install --upgrade pip
          pip install github-readme-terminal

      - name: Run script
        run: python gen.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIFOS_GENERAL_COLOR_SCHEME: "dracula"

      - name: Update gif
        run: |
          git add output.gif
          git -c "user.name='time update'" -c "user.email='i@am.bot'" commit -m "Refreshed to $(TZ='Europe/Warsaw' date)"
          git push
